modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "foxified_networking"
version = "${version}"
displayName = "Foxified Networking API"
authors = "TexTrue"
description = '''
Low-level, vanilla protocol oriented networking hooks.
'''
logoFile = "icon.png"

[[dependencies.foxified_networking]]
modId = "neoforge"
type = "required"
versionRange = "[21.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.foxified_networking]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "fabric-networking-api-v1.mixins.json"

[[mixins]]
config = "fabric-networking-api-v1.client.mixins.json"
